version: '3.8'

services:
  web:
    build: .
    ports:
      - "8004:8004"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.development
    volumes:
      - .:/app
      - /opt/configs/.financebuddy_env:/app/.env
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
