version: '3.8'

services:
  web:
    build: .
    ports:
      - "8004:8004"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.development
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
