version: "3.8"

services:
  web:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ../locales:/app/locales
    ports:
      - "8004:8004"
    restart: unless-stopped
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M

  webhook_setup:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    env_file:
      - .env
    command: python manage.py set_webhook
    restart: on-failure
    networks:
      - app_network

volumes:
  static_volume:
  media_volume:

networks:
  app_network:
    driver: bridge
