name: CI/CD Pipeline for Finance Buddy

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # - name: Run tests
    #   env:
    #     SECRET_KEY: ${{ secrets.SECRET_KEY }}
    #     DEBUG: 'False'
    #     TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    #     WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
    #   run: |

    #     python manage.py test

    - name: Deploy to Production Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo echo "Hello World!"
          sudo mkdir -p /projects/FinanceBuddy
          cd /projects/FinanceBuddy || exit 1
          sudo git fetch origin dev && sudo git reset --hard origin/dev
          cp docker-compose-dev.yml docker-compose.yml
          sudo docker-compose || true
          sudo docker-compose up -d --build
          sudo systemctl reload nginx
          sudo docker image prune -f
